# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b770319187d6f4f437a6a9a7c7bc0cd07de3b5fb4e5ef6470de1a4b0dd570ec9052ac697294fd42a69447b5bb9c448ae23d0379668b7ebdab91f84826c93c84c

test:
  secret_key_base: e266b9283c29d3b2835f6a8dcf78678f61a09a5e7ee7de37bc27929f3fc00fb6d9c7a55c979a0a0ee0d34ab540cc0a9463bf6e89fa80eaaf4dd6df59c9ae9eea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
